name: Problem Report
description: Report a problem with FluidNC
title: "Problem: "
labels: ["triage"]
body:
- type: markdown
  attributes:
    value: Please fill in the forms below.  The better the information you provide, the better we can help you. Information that you might think is irrelevant is often the key to solving the problem.
- type: textarea
  id: controller-board
  attributes:
    label: Controller Board
    description: |
      Tell us which controller board you are using, for example 6-pack, MPCNC, MKS DLC32, XPro V5, etc.
      If it is a custom board of your own design, tell us all about it and, if possible, provide a 
      photograph and a link to schematics.
    value: 6-pack
  validations:
    required: true
- type: textarea
  id: machine-description
  attributes:
    label: Machine Description
    description: Tell us about your machine - is it a mill, router, laser engraver, or what?
    placeholder: Gantry router with external DM542 stepper drivers, dual Y motors, optical endstops on all axes.  Spindle is a DeWalt DW618M router.
  validations:
    required: true
- type: textarea
  id: configuration-file
  attributes:
    label: Configuration file
    description: Paste the contents of your machine configuration file (.yaml) here
    placeholder: <Paste config file contents here>
    render: yaml
  validations:
    required: true
- type: textarea
  id: boot-messages
  attributes:
    label: Startup Messages
    description: Paste the startup messages here.  You can see them by sending "$ss" from FluidTerm, WebUI Console, or any sender's console.
    placeholder: <Paste startup messages here>
    render: shell
  validations:
    required: true
- type: input
  id: user-interface
  attributes:
    label: User Interface Software
    description: What user interface software are you using?
    placeholder: E.g. WebUI, FluidTerm, UGS, Candle, ...
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Tell use exactly what you did, what you expected to happen, and what happened instead.  The more detail, the better.
    placeholder: I did something, expected this, and that happened
  validations:
    required: true
- type: textarea
  id: other-info
  attributes:
    label: Other Information
    description: Please add any other information that might help us understand your situation.  Context is crucial!
    placeholder: Log messages from the console, screenshots, or anything else of interest.
